### ISSUE TITLE
Synchronisation problems between Gazebo and estimation threads

### ISSUE THREAD

**Issue by DanielePucci** [robotology/wb-toolbox#26]
**Description:**
The Gazebo simulation and the estimation threads in charge of estimating joint position/velocities/etc are not synchronised even when using the appropriate block, and this introduces an undesired machine-dependence of the controllers performances.

@traversaro @francesco-romano 

---

**Further Information**:
- _System Information:_ `Darwin Danieles-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64`
- _Working branch:_ `master`
- _Current commit:_ `cc53fb3c750899a0dddcae413a9484a6dfee24b4`
- _YARP ROOT:_ `/Users/DanielePucci/src/yarp`
- _ICUB_ROOT:_ `/Users/DanielePucci/src/icub-main`
- _YARP_DATA_DIRS:_ `/Users/DanielePucci/src/install/share/yarp:/Users/DanielePucci/src/install/share/iCub:/Users/DanielePucci/src/codyco-superbuild/build/install/share/codyco:/Users/DanielePucci/src/install/share/ICUBcontrib`
- _YARP_ROBOT_NAME:_ `iCubGenova05`
- _Yarp Installation:_ `/Users/DanielePucci/src/install/bin/yarpserver`
- _LD_LIBRARY_PATH:_``
- _LD_PRELOAD:_``
- _DYLD_INSERT_LIBRARIES:_``

**Comment by traversaro** [comment]
The `/clock` port is still published by the `gazebo_yarp_clock` plugin, even if the simulation is paused and stepped by the simulink gazebo synchronization block. 
Starting MATLAB prepending the `matlab` command with `YARP_CLOCK=/clock` should solve the issue, however I don't know if there is any issue with that with our current workflow.
@DanielePucci suggested using `setenv` to set the `YARP_CLOCK` enviromental variable, however it should investigated if that is sufficent, as the `YARP_CLOCK` enviromental variable is readed only in the yarp init function : https://github.com/robotology/yarp/blob/0e862d8daec639d74d94f79460f7c21aff619072/src/libYARP_OS/src/Network.cpp#L620 .

**Comment by traversaro** [comment]
cc @gabrielenava @S-Dafarra

**Comment by Yeshasvitvs** [comment]
@diegoferigo FYI

**Comment by francesco-romano** [comment]
https://github.com/robotology/WB-Toolbox/issues/46 should fix this issue

**Comment by diegoferigo** [comment]
@DanielePucci The ImpedanceControl didn't have `YARP_CLOCK` set. Exporting this variable will affect the filtering of the speed signal we talked about f2f, and it is an alternative solution of setting the `readSpeedAccFromControlBoard` variable in `yarpWholeBodyInterface.ini`.

**Comment by DanielePucci** [comment]
Mmmm it seems weird to me since I'm pretty sure that `torqueBalancing` back in time did have the synchroniser correctly set.

**Comment by diegoferigo** [comment]
The synchronizer is a different thing as far as I understood. Despite processes are spawned by simulink, which controls gazebo stepping through the syncronizer you mentioned, they run by default using the system clock. In order to sync them with simulink, using `YARP_CLOCK` is required. It is a complicated loop, but in this way `YARP_CLOCK` is taken from gazebo, which is set step after step as said by simulink.

**Comment by traversaro** [comment]
I think this was solved in https://github.com/robotology/wb-toolbox/pull/56 .

**Comment by diegoferigo** [comment]
PR #56 removed the abstraction layer provided by the `whole-body-interface`. In its `yarp` implementation we were filtering the estimated quantities with tunable low-pass filters.

Right now the measurements provided by the _GetMeasurement_ block are the raw signals, and it is user's responsibility to filter them properly with the _DiscreteFilter_ introduced in #47.

This does not mean that the `YARP_CLOCK` env variable should not be set, we still need it in order to set the network clock as the default clock. I remember that during the last year the clock functionality in YARP has been rewritten, I'm not sure if I am missing something. @traversaro

**Comment by diegoferigo** [comment]
I think this issue can be closed since the solution is to use the `YARP_CLOCK` env variable. In order to avoid it, we should go towards #164.
