### ISSUE TITLE
The YARP to DOF converter should label the output ports

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/wb-toolbox#70]
This goes in the direction of reducing possible source of misunderstanding when connecting this block to a scope, especially when the user does not remember/know the control boards order.

**Comment by diegoferigo** [comment]
This feature would require the block to access the closest _Configuration_ block and read the order or the ControBoards list. It is doable without a big effort.

However, I will wait a bit before implementing it because it is somehow related to changes related to the coming automatic code generation support and its impact on block's masks.

**Comment by diegoferigo** [comment]
This block has been removed from the toolbox in PR https://github.com/robotology/wb-toolbox/pull/147 in favor of user logic directly in Simulink. Closing.
